[package]
name = "stream-to-journald"
version = "0.1.0"
authors = ["Steven Davies <github@steev.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systemd = "0.8.2"
log = "0.4.13"
